### ISSUE TITLE
Switch to a CSS-based method of hiding MenuFlyouts.

### ISSUE THREAD

**Issue by Tropix126** [Tropix126/fluent-svelte#12]
Currently, we are actually removing the anchor from the DOM, however this causes issues with the checkbox and radio items being reset on every open. I'm not sure if this is should be considered as intended, but it's certainly not expected behavior. Anyways, I plan to use `display: none;` instead of if-blocks to preserve input state across opens.

**Comment by JLAcostaEC** [comment]
I don't know if my comment is helpful, but applying a display: none would make the element untransitionable, you should use a set of opacity and pointerEvents or use transform: scale(0) + PointerEvents: none. Greetings

**Comment by Tropix126** [comment]
Think i'm going to close this as intended. If anyone has further thoughts on this, feel free to open another issue.
