### ISSUE TITLE
[Website] "View GitHub" button doesn't open the repo

### ISSUE THREAD

**Issue by Rexogamer** [Tropix126/fluent-svelte#15]
### Before you start...

- [X] Have you updated your dependencies? You might be using an old version of the library.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox Beta/Dev/Nightly

### Description

The "View GitHub" button on the project's website doesn't open the repo.

### Steps To Reproduce

1. Go to [the official website](https://fluent-svelte.vercel.app/)
2. Click the "View GitHub" button

### Expected behavior

Upon clicking the button, the repo is opened.

### Relevant Assets

![image](https://user-images.githubusercontent.com/42586271/149676491-973b2da6-c0fa-4b3a-ad1f-c45a65f5deb3.png)

**Comment by Tropix126** [comment]
Thanks for finding this, it should be fixed as of https://github.com/Tropix126/fluent-svelte/commit/cd618886a891c47ab11d2edcbb43ed74d05c6d19.
