### ISSUE TITLE
Disabled not affecting TextBox inside NumberBox

### ISSUE THREAD

**Issue by Odonno** [Tropix126/fluent-svelte#17]
### Before you start...

- [X] Have you updated your dependencies? You might be using an old version of the library.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Microsoft Edge

### Description

When using the property `disabled` of `NumberBox`, we can still update the text inside the `TextBox`, whether the property is `true` or `false`.

### Expected behavior

When `disabled` is set to true, we should not be able to update the text inside the `TextBox`.

**Comment by Tropix126** [comment]
Thanks for finding this! I've located the issue and fixed it locally; will keep you updated.

**Comment by Tropix126** [comment]
Have pushed a fix; expect it to be working in the next release.

**Comment by Tropix126** [comment]
> Hello @Tropix126
> 
> When do you expect to publish a new version of the lib?

I plan for it to be out by the end of today :)

**Comment by Tropix126** [comment]
Fixed as of 1.3.0.
