### ISSUE TITLE
Slider: input and change events not forwarded

### ISSUE THREAD

**Issue by JVariance** [Tropix126/fluent-svelte#31]
### Before you start...

- [X] Have you updated your dependencies? You might be using an old version of the library.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Description

on:change and on:input event handlers on the Slider Component don't work.

See: https://svelte.dev/repl/833c79a8f04e497a80ed52ff2868978c?version=3.46.4

### Expected behavior

On:change and on:input events should be forwarded.

**Comment by JVariance** [comment]
For now I modified the Slider.svelte file with an reactive onChange(value) function as shown on https://graphcms.com/blog/data-binding-in-svelte.

**Comment by Tropix126** [comment]
Found the problem, events are forwarded to the outer `<div>` container. This is intentional, although I forgot to forward the input-specific events to the slider's <input> element. Should be an easy fix.

**Comment by Tropix126** [comment]
After further investigation it seems that <input> elements need to be modified via user interaction (vs programmatic value setting) for `change` and `input` events to be fired. I've pushed a change that dispatches a custom change event for `<Slider />`. Closing as this will be fixed in the next publish.

**Comment by JVariance** [comment]
@Tropix126 Unfortunately the event target and therefor the value aren't accessible in the CustomEvent returned from the Slider Component.
