### ISSUE TITLE
Textbox action button not centered

### ISSUE THREAD

**Issue by frostmint** [Tropix126/fluent-svelte#37]
### Before you start...

- [X] Have you updated your dependencies? You might be using an old version of the library.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

This happening in Fluent Svelte-REPL (i just testing)
<img width="292" alt="Screenshot 2022-03-05 124413" src="https://user-images.githubusercontent.com/90097027/156870021-c1b18850-de61-460c-9f22-3ccbb993aac6.png">

### Expected behavior

I expect the icon is centered like in the [Fluent Svelte Web](https://fluent-svelte.vercel.app/docs/components/textbox)
<img width="156" alt="Screenshot 2022-03-05 124324" src="https://user-images.githubusercontent.com/90097027/156870061-7f39b6b7-0e04-4502-abf4-9a3a4efa2a99.png">

**Comment by Tropix126** [comment]
Seems to be caused by some global styles added by the Svelte REPL. I've updated the REPL example with a quick hotfix.

```css
:global(button) {
	margin: initial;
}```
