### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Tropix126** [Tropix126/fluent-svelte#5]
We're going to ideally need a logo before the production release of the library. Using either the Svelte logo or Fluent Design logo directly with some recolors isn't really an option.

**Comment by lorisobi** [comment]
![grafik](https://user-images.githubusercontent.com/28399150/142828701-8ee2e39d-2c00-4e99-b6ae-104d4be52952.png)
Using both the Svelte logo and Fluent Design logo directly with some recolors

**Comment by nikolai-cc** [comment]
To the right is the logo MS uses on fluent.microsoft.com, to the left an implementation of the svelte logo in the same style.

Won't work on small sizes though (as does the ms image)

<img width="666" alt="Screen_Shot_2021-11-20_at_12 08 55" src="https://user-images.githubusercontent.com/17435776/143463531-1146ae41-ccd9-4864-9dbb-669c6e4d0e68.png">

**Comment by nikolai-cc** [comment]
Actually I found out they *do* have a smaller icon, which they use inside their figma design files ([found here](https://developer.microsoft.com/en-us/fluentui#/resources)).

Made a version of that, in both fluent-logo and svelte colours, along with a ribbon idea which might not completely fit the style, but the forms reminded me of, and I really like the look of.

![Screen Shot 2021-11-25 at 16 16 37](https://user-images.githubusercontent.com/17435776/143466719-609d7ebe-d0e2-4758-a113-47424c9049e0.png)
from left to right:
1. fluent logo
2. svelte-logo in fluent style with the fluent gradient applied
3. svelte-logo in fluent style with the colour grabbed from the svelte page
4. ribbon idea with random colours from fluent palette
5. ribbon idea with slight gradient for depth based on the same colours as 4.

**Comment by nikolai-cc** [comment]
Wondering how they would look on a black or a white background? So was I!

![Screen Shot 2021-11-25 at 16 28 30](https://user-images.githubusercontent.com/17435776/143468272-285fd16a-4a3b-4798-9731-53d7dc09513e.png)

**Comment by nikolai-cc** [comment]
And finally a couple that have been recoloured based on --fds-accent-base (+dark / light)

<img width="701" alt="Screen Shot 2021-11-25 at 19 41 16" src="https://user-images.githubusercontent.com/17435776/143489399-01f36ca7-fde1-4599-9448-16d61de9b399.png">

**Comment by Tropix126** [comment]
Thanks for everyone's contributions to this 🙂. For the time being, I've decided to use @lorisobi's design, because of how the weight/colors blend well with the new site.
